
include: package:strict/analysis_options.yaml
analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    argument_type_not_assignable: false
    implicit_dynamic_map_literal: false
    implicit-dynamic: false
    avoid_dynamic_calls: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    unnecessary_getters_setters: false
    non_constant_identifier_names: false
    avoid_catching_errors: false
    use_build_context_synchronously: false
    prefer_final_locals: false
    cascade_invocations: false
    public_member_api_docs: true
